name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: âš™ï¸ configure unit test
        run: |
          mkdir -p build/test
          cd build/test
          cmake ../../test
      - name: ğŸ› ï¸ build unit test
        run: |
          cd build/test
          cmake --build .
      - name: ğŸ§ª run unit test
        run: |
          cd build/test
          ./tests
      - name: âš™ï¸ configure build
        run: |
          cd build
          cmake ..
      - name: ğŸ› ï¸ build
        run: |
          cd build
          cmake --build .
